<?php

/**
 * BaseJobState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Job
 * 
 * @method integer             getId()   Returns the current record's "id" value
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getJob()  Returns the current record's "Job" collection
 * @method JobState            setId()   Sets the current record's "id" value
 * @method JobState            setName() Sets the current record's "name" value
 * @method JobState            setJob()  Sets the current record's "Job" collection
 * 
 * @package    azine
 * @subpackage model
 * @author     DominikBusinger
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseJobState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_state');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Job', array(
             'local' => 'id',
             'foreign' => 'state'));
    }
}