# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  error_404_action: error404
  error_404_module: error

  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  sf_guard_plugin_routes_register: false
  sf_guard_extra_plugin_from:   no-reply@azine.me


  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            13359271bbcb94ad08391f70d4399b29aa884c32

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    enabled_modules:        [default, sfGuardAuth, sfGuardForgotPassword, sfGuardRegister]        

    login_module:           sfGuardAuth
    login_action:           signin
        
    secure_module:          sfGuardAuth
    secure_action:          secure
    
    # set the default culture to german
    default_culture:        de        # Default user culture

    # define helpers that are used all the time.
    standard_helpers:       [Partial, Cache, I18N]
    
    