<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/30 16:38:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=azine_dev',
  'username' => 'dominik',
  'password' => 'sd*%fhg7',
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
