<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/30 16:38:58
sfConfig::add(array(
  'app_languages' => array (
  'en' => 'en',
  'de' => 'de',
),
  'app_sfLanguageSwitch_flagPath' => '/sfLanguageSwitchPlugin/images/flag',
  'app_sfLanguageSwitch_availableLanguages' => array (
  'de' => 
  array (
    'title' => 'Deutsch',
  ),
  'en' => 
  array (
    'title' => 'English',
    'image' => '/sfLanguageSwitchPlugin/images/flag/gb.png',
  ),
),
));
