all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=azine_dev'
      username: dominik
      password: sd*%fhg7
      encoding: utf8
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=azine_prod'
      username: dominik
      password: sd*%fhg7
      encoding: utf8
      
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=azine_test'
      username: dominik
      password: sd*%fhg7
      encoding: utf8
      