<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/30 16:35:22
sfConfig::add(array(
  'app_user_notification_modes' => array (
  1 => 'instantly',
  2 => 'twice per day',
  3 => 'once per day',
  4 => 'twice per week',
  5 => 'once per week',
  9 => 'never',
),
  'app_sfLanguageSwitch_flagPath' => '/sfLanguageSwitchPlugin/images/flag',
  'app_sfLanguageSwitch_availableLanguages' => array (
  'de' => 
  array (
    'title' => 'Deutsch',
  ),
  'en' => 
  array (
    'title' => 'English',
    'image' => '/sfLanguageSwitchPlugin/images/flag/gb.png',
  ),
),
  'app_sf_guard_extra_plugin_from' => 'no-reply@azine.me',
  'app_sf_guard_plugin_success_signout_url' => '@welcome',
  'app_upload_dir_name' => 'uploads',
  'app_job_att_upload_dir' => 'jobAttachments',
));
