<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/30 16:36:34
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
