<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/30 16:37:17
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
