# charset settings
options:
  collate: utf8_unicode_ci
  charset: utf8

# sfGuardUser um einige Felder ergaenzen.
sfGuardUser:
  actAs:
    Sluggable:
      fields: [first_name, last_name]
  columns:
    first_name:          string(20)                                      # Vorname
    last_name:           string(20)                                      # Nachname
    open_id:             string(255)                                     # url oder email fuer Open-ID Authentifizierung
    notification_mode:  { type: integer(2), default: 2, notnull: true}   # Haeufigkeit der Benachrichtigung (0: off, 1: sofort, 2: daily, 3: weekly)
    cv_url:              string(255)                                     # URL zum online-CV

Job:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
    Timestampable: ~
  columns:
    id:                 { type: integer(6), primary: true, notnull: true, autoincrement: true }
    state:              { type: integer(2), notnull: true }                     # Status des Jobs
    user_id:            { type: integer(4), notnull: true }                     # Submitter des Jobs
    title:              { type: string(200), notnull: true }                    # Titel des Jobs
    description:        { type: clob, notnull: true }                           # Job-Beschreibung
    attachment:         { type: string(255), notnull: false }                   # Name eines allfaelligem Attachments
    required_skills:    { type: string(255), notnull: false }                   # Benoetigte Skills als CSV
    start_date:			{ type: date, notnull: true }							# start Datum des Engagements
    end_date:			{ type: date, notnull: false }							# End Datum des Engagements
    fte:				{ type: integer(3), notnull: true, default 100 }		# Stellenprozente
  relations:
    User: { class: sfGuardUser, local: user_id, foreign: id, onDelete: CASCADE }
    JobState: { class: JobState, local: state, foreign: id, onDelete: CASCADE }

Application:
  actAs:
    Timestampable: ~
  columns:
    id:                 { type: integer(6), primary: true, notnull: true, autoincrement: true } # ID der Bewerbung
    job_id:             { type: integer(6), notnull: true }                                     # ID des Jobs
    applicant_id:       { type: integer(4), notnull: true }                                     # ID des Freelancers der sich fuer den Job bewirbt
    requested_rate:     { type: integer(6) }                                                    # Rate die der Freelancer will
    rate_type:          { type: string(20), default: daily }                                    # Tages oder Stundensatz
    application_text:   { type: clob, notnull: true }                                           # Bewerbungstext
    cv_attachment:      { type: blob }                                                          # Blob mit allfaelligem CV-Attachment. 
  relations:
    User: { class: sfGuardUser, local: applicant_id, foreign: id, onDelete: CASCADE }
    Job: { class: Job, local: job_id, foreign: id, onDelete: CASCADE }

JobState:
  columns:
    id:                 { type: integer(2), primary: true, notnull: true, autoincrement: true }
    name:               { type: string(20) }
